package:
  name: "surropt"
  version: "0.0.12"

source:
  git_url: https://github.com/feslima/surropt.git

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} setup.py install"

requirements:
  host:
    - colorama >=0.4.1,<0.5.0
    - cyipopt >=1.0.3,<2.0.0
    - numpy >=1.15.0,<2.0.0
    - pip
    - pydace >=0.1.3,<0.2.0
    - pydoe2 >=1.2.1,<2.0.0
    - python
    - requests >=2.20.1,<3.0.0
    - scipy >=1.2.0,<2.0.0
  run:
    - colorama >=0.4.1,<0.5.0
    - cyipopt >=1.0.3,<2.0.0
    - numpy >=1.15.0,<2.0.0
    - pydace >=0.1.3,<0.2.0
    - pydoe2 >=1.2.1,<2.0.0
    - python
    - requests >=2.20.1,<3.0.0
    - scipy >=1.2.0,<2.0.0

test:
  imports:
    - surropt
    - surropt.caballero
    - surropt.core
    - surropt.core.nlp
    - surropt.core.options
    - surropt.core.procedures
    - surropt.core.utils
    - surropt.utils

about:
  home: "https://github.com/feslima/surropt"
  license: Apache Software
  license_family: APACHE
  license_file: 
  summary: "Surrogate optimization toolbox for time consuming models"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
